// Converts migrate/export.json (from export-from-sheet.gs) into migrate/seed.sql
// Usage: node migrate/generate-seed.js
const fs = require('fs');
const path = require('path');

const exportPath = path.join(__dirname, 'export.json');
if (!fs.existsSync(exportPath)) {
  console.error('migrate/export.json not found - run export-from-sheet.gs first and save its output there.');
  process.exit(1);
}

const { products, inventory } = JSON.parse(fs.readFileSync(exportPath, 'utf8'));
const esc = s => "'" + String(s).replace(/'/g, "''") + "'";

const lines = [];
lines.push('-- generated by migrate/generate-seed.js - one-time import, do not edit by hand');
lines.push('');

products.forEach(p => {
  lines.push(
    `INSERT INTO products (product, type, manufacturing, count, added_on) VALUES ` +
    `(${esc(p.product)}, ${esc(p.type)}, ${esc(p.manufacturing)}, ${Number(p.count)}, ${esc(p.added_on)}) ` +
    `ON CONFLICT(product, type) DO UPDATE SET manufacturing=excluded.manufacturing, count=excluded.count;`
  );
});

lines.push('');

inventory.forEach(r => {
  lines.push(
    `INSERT INTO inventory (product, type, count_date, count, logged_at) VALUES ` +
    `(${esc(r.product)}, ${esc(r.type)}, ${esc(r.count_date)}, ${Number(r.count)}, ${esc(r.logged_at)}) ` +
    `ON CONFLICT(product, type, count_date) DO UPDATE SET count=excluded.count, logged_at=excluded.logged_at;`
  );
});

fs.writeFileSync(path.join(__dirname, 'seed.sql'), lines.join('\n') + '\n');
console.log(`Wrote migrate/seed.sql: ${products.length} products, ${inventory.length} inventory rows.`);
